"""weather2

Revision ID: fec16d67231b
Revises: 2e6b65590c2b
Create Date: 2025-02-26 16:33:00.618002

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fec16d67231b"
down_revision: Union[str, None] = "2e6b65590c2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_records",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_records")),
        sa.UniqueConstraint(
            "username", name=op.f("uq_weather_records_username")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weather_records")
    # ### end Alembic commands ###
